### PR TITLE
darui

### PR DESCRIPTION
**Pull request by yuua**
## darui
- 3行とかだるいのでワンライナーに変更する

### CODE REVIEW

**Comment by hadashiA** [comment]
I am also the same idea.
However, this ruby code's concept is to express 'だるさ'.
I think previous `loop do ... end` version is `だるそう` than `until` version. (´･_･`)…
What do you think?

**Comment by yuua** [comment]
Thank you @hadashiA 
I think so too.
However, Since the very languid 
May I merge?

**Comment by hadashiA** [comment]
Yup. I feel darui.  trying quickly merge.  👺 👍  👺

**Comment by yuua** [comment]
Thank you!!!! 🌊 👍

**Comment by mapyo** [comment]
I have confirmed that there is no commit after the ok comment 👍

**Pull request merged**
